<?php
/**
 * Centro Nacional de Desarrollo e Investigación de Tecnologías Libres (CENDITEL)
 * CENDITEL, Mérida - Venezuela
 * Dirección de Desarrollo
 * Módulo Drupal para crear un formulario simple para consultar información en la base de datos
 * @author Ing. Angelo Osorio
 * @date 2017-10-19 // (dd,mm,yyyy)
 * @version 1.-dev // (1.0)
 * @file formulario_consulta.module
 */





/**
 * Implementación del hook_menu().
 * Crea un enlace a la página de consulta formulario_consulta_hola()
 */
function formulario_consulta_menu(){
  $items['formulario_consulta'] = array(
    'title' => 'Formulario de consulta',
    'page callback' => 'formulario_consulta_hola',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}



/**
 * Callback para formulario_consulta_listar.
 */
function formulario_consulta_listar() {

  $results = db_query('SELECT * FROM datos_formulario ORDER BY cedula');
  $salida = "";
  foreach($results as $res){
    //$salida = $salida."[Código] = ".$res->nombre."  [Nombre] = ".$res->apellido."<br>";
    $salida = $salida."<tr>";
    $salida = $salida."<td>".$res->nombre."</td>";
    $salida = $salida."<td>".$res->apellido."</td>";
    $salida = $salida."<td>".$res->cedula."</td>";
    $salida = $salida."<td>".$res->direccion."</td>";
    $salida = $salida."<td>".$res->empleo."</td>";
    $salida = $salida."<td>".$res->vocacion."</td>";
    $salida = $salida."<td>".$res->educacion."</td>";
    $salida = $salida."</tr>";
  }
  //$salida = "</table>";
  return $salida;
}


function formulario_consulta_hola() {
  $variables = array(
    'message' => formulario_consulta_listar(),
  );
  return theme('formulario_consulta_hola', $variables);
}

function formulario_consulta_theme() {
  return array(
    'formulario_consulta_hola' => array(
      'template' => 'formulario_consulta',
    ),
  );
}