<?php
/**
 * Centro Nacional de Desarrollo e Investigación de Tecnologías Libres (CENDITEL)
 * CENDITEL, Mérida - Venezuela
 * Dirección de Desarrollo
 * Módulo Drupal para crear un formulario simple para editar información en la base de datos
 * @author Ing. Angelo Osorio
 * @date 2017-10-19 // (dd,mm,yyyy)
 * @version 1.-dev // (1.0)
 * @file formulario_inserta.module
 */





/**
 * Implementación del hook_menu().
 * Crea un enlace al formulario formulario_inserta_form()
 */
function formulario_edita_menu(){
  $items['formulario_edita'] = array(
    'title' => 'Formulario de edición',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('formulario_edita_form'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['formulario_elige_edita'] = array(
    'title' => 'Formulario de selección de edición',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('formulario_elige_edita_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}


/**
 * Implements hook_form().
 */
function formulario_edita_form(){

  $personas = buscapersonas($_SESSION["cedula"]);
  // Datos Personales - Fieldset
  $form['datos_personales'] = array(
    '#type' => 'fieldset',
    '#title' => t('Datos Personales'),
    '#collapsible' => TRUE,
  );
  // Datos Personales - Nombre
  $form['datos_personales']['nombre'] = array(
    '#title' => t('Nombre'),
    '#type' => 'textfield',
    '#description' => t('Nombre del usuario'),
    '#maxlength' => 50,
    '#required' => TRUE,
    '#default_value' => $personas['nombre'],
  );
  // Datos Personales - Apellido
  $form['datos_personales']['apellido'] = array(
    '#title' => t('Apellido'),
    '#type' => 'textfield',
    '#description' => t('Apellido del usuario'),
    '#maxlength' => 50,
    '#required' => TRUE,
    '#default_value' => $personas['apellido'],
  );
  // Datos Personales - Cédula
  $form['datos_personales']['cedula'] = array(
    '#title' => t('Cédula'),
    '#type' => 'textfield',
    '#description' => t('Cédula del usuario'),
    '#maxlength' => 8,
    '#required' => TRUE,
    '#default_value' => $personas['cedula'],
    '#disabled' => TRUE,
  );
  // Datos Personales - Dirección
  $form['datos_personales']['direccion'] = array(
    '#title' => t('Dirección'),
    '#type' => 'textfield',
    '#description' => t('Dirección del usuario'),
    '#maxlength' => 255,
    '#required' => TRUE,
    '#default_value' => $personas['direccion'],
  );
  // Datos Laborales - Fieldset
  $form['datos_laborales'] = array(
    '#type' => 'fieldset',
    '#title' => t('Datos Laborales'),
    '#collapsible' => TRUE,
  );
  // Datos Laborales - Empleo
  $form['datos_laborales']['empleo'] = array(
    '#title' => t('Empleo'),
    '#type' => 'select',
    '#description' => t('¿Tiene Empleo?'),
    '#options' => drupal_map_assoc(array(t('Sí'), t('No'))),
    '#required' => TRUE,
    '#default_value' => $personas['empleo'],
  );
  // Datos Laborales - Vocación
  $form['datos_laborales']['vocacion'] = array(
    '#title' => t('Vocación'),
    '#type' => 'textfield',
    '#description' => t('¿A qué se dedica?'),
    '#maxlength' => 50,
    '#required' => TRUE,
    '#default_value' => $personas['vocacion'],
  );
  // Datos Laborales - Educación
  $form['datos_laborales']['educacion'] = array(
    '#title' => t('Educación'),
    '#type' => 'select',
    '#description' => t('Grado de instrucción'),
    '#options' => grados(),
    '#required' => TRUE,
    '#default_value' => $personas['educacion'],
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Enviar'),
  );
  return $form;
}

/**
 * Handle post_validate form submission.
 */
function formulario_edita_form_submit(&$form, &$form_state){
  //db_query("UPDATE {ente_actividad} SET nombre = '%s' WHERE id_actividad = %d", check_plain($form_state['values']['nombre']), $form_state['values']['id_actividad']);
  //drupal_set_message(t('Actividad %name_actividad modificada', array('%name_actividad' => $form_state['values']['nombre'])));
  //$form_state['redirect'] = 'admin/settings/ente_planificador/actividades';
  $nombre = $form_state['values']['nombre'];
  $apellido = $form_state['values']['apellido'];
  $cedula = $form_state['values']['cedula'];
  $direccion = $form_state['values']['direccion'];
  $empleo = $form_state['values']['empleo'];
  $vocacion = $form_state['values']['vocacion'];
  $educacion = $form_state['values']['educacion'];
  db_update('datos_formulario')
    //->fields(array('nombre', 'apellido', 'cedula', 'direccion', 'empleo', 'vocacion', 'educacion'))
    ->fields(array('nombre' => $nombre, 'apellido' => $apellido, 'cedula' => $cedula, 'direccion' => $direccion, 'empleo' => $empleo, 'vocacion' => $vocacion, 'educacion' => $educacion,))
    ->condition('cedula', $cedula,'=')
    ->execute();
  drupal_set_message(t('%apellido, %nombre CI: %cedula, Vive en: %direccion, %empleo posee empleo, es %vocacion, Grado educacional: %educacion ',array('%nombre' => $nombre, '%apellido' => $apellido, '%cedula' => $cedula, '%direccion' => $direccion, '%empleo' => $empleo, '%vocacion' => $vocacion, '%educacion' => $educacion )));
}


/**
 * Implements hook_form().
 */
function formulario_elige_edita_form(){

  $cedula = buscacedula();
  // Datos Personales - Cédula
  $form['cedulaseleccionada'] = array(
    '#title' => t('Elija la cédula de la persona que va a editar'),
    '#type' => 'select',
    '#required' => TRUE,
    '#options' => $cedula,
    //'#default_value' => $personas['cedula'],
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Enviar'),
  );
  return $form;
}

/**
 * Handle post_validate form submission.
 */
function formulario_elige_edita_form_submit(&$form, &$form_state){
  $_SESSION["cedula"] = $form_state['values']['cedulaseleccionada'];
  $form_state['redirect'] = 'formulario_edita';
}




// Select * FROM datos_formulario WHERE cedula = $cedula
function buscapersonas($cedula) {
  if (!isset($cedula)) { $cedula = 0; }
  $query = db_select('datos_formulario', 'd')
    ->fields('d', array())
    ->condition('cedula', $cedula,'=')
    ->execute();
  while($record = $query->fetchAssoc()) {
    $resultado = $record;
  }
  return $resultado;
}

function buscacedula() {
  $query = db_select('datos_formulario', 'd') ->fields('d', array()) ->execute();
  while($record = $query->fetchAssoc()) {
    $resultado[] = $record["cedula"];
  }
  return drupal_map_assoc($resultado);
}