<?php
/**
 * Centro Nacional de Desarrollo e Investigación de Tecnologías Libres (CENDITEL)
 * CENDITEL, Mérida - Venezuela
 * Dirección de Desarrollo
 * Módulo Drupal para crear un formulario simple para introducir información en la base de datos
 * @author Ing. Angelo Osorio
 * @date 2017-10-19 // (dd,mm,yyyy)
 * @version 1.-dev // (1.0)
 * @file formulario_inserta.module
 */





/**
 * Implementación del hook_menu().
 * Crea un enlace al formulario formulario_inserta_form()
 */
function formulario_inserta_menu(){
  $items['formulario_inserta'] = array(
    'title' => 'Formulario de inserción',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('formulario_inserta_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}



/**
 * Implements hook_form().
 */
function formulario_inserta_form(){

  // Datos Personales - Fieldset
  $form['datos_personales'] = array(
    '#type' => 'fieldset',
    '#title' => t('Datos Personales'),
    '#collapsible' => TRUE,
  );
  // Datos Personales - Nombre
  $form['datos_personales']['nombre'] = array(
    '#title' => t('Nombre'),
    '#type' => 'textfield',
    '#description' => t('Nombre del usuario'),
    '#maxlength' => 50,
    '#required' => TRUE,
  );
  // Datos Personales - Apellido
  $form['datos_personales']['apellido'] = array(
    '#title' => t('Apellido'),
    '#type' => 'textfield',
    '#description' => t('Apellido del usuario'),
    '#maxlength' => 50,
    '#required' => TRUE,
  );
  // Datos Personales - Cédula
  $form['datos_personales']['cedula'] = array(
    '#title' => t('Cédula'),
    '#type' => 'textfield',
    '#description' => t('Cédula del usuario'),
    '#maxlength' => 8,
    '#required' => TRUE,
  );
  // Datos Personales - Dirección
  $form['datos_personales']['direccion'] = array(
    '#title' => t('Dirección'),
    '#type' => 'textfield',
    '#description' => t('Dirección del usuario'),
    '#maxlength' => 255,
    '#required' => TRUE,
  );
  // Datos Laborales - Fieldset
  $form['datos_laborales'] = array(
    '#type' => 'fieldset',
    '#title' => t('Datos Laborales'),
    '#collapsible' => TRUE,
  );
  // Datos Laborales - Empleo
  $form['datos_laborales']['empleo'] = array(
    '#title' => t('Empleo'),
    '#type' => 'select',
    '#description' => t('¿Tiene Empleo?'),
    '#options' => drupal_map_assoc(array(t('Sí'), t('No'))),
    '#required' => TRUE,
  );
  // Datos Laborales - Vocación
  $form['datos_laborales']['vocacion'] = array(
    '#title' => t('Vocación'),
    '#type' => 'textfield',
    '#description' => t('¿A qué se dedica?'),
    '#maxlength' => 50,
    '#required' => TRUE,
  );
  // Datos Laborales - Educación
  $form['datos_laborales']['educacion'] = array(
    '#title' => t('Educación'),
    '#type' => 'select',
    '#description' => t('Grado de instrucción'),
    '#options' => grados(),
    '#required' => TRUE,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Enviar'),
  );
  return $form;
}


function grados(){
  return drupal_map_assoc(array(
    t('Sin educación'),
    t('Educación Primaria Incompleta'),
    t('Educación Primaria'),
    t('Educación Secundaria Incompleta'),
    t('Educación Secundaria'),
    t('Bachillerato Incompleta'),
    t('Bachillerato'),
    t('Universitaria Incompleta'),
    t('Universitaria'),
    t('Postgrado'),
    t('Magister'),
    t('Doctorado'),
    t('Post-Doctorado'),
  ));
}



// Función para validar el formulario 
// function formulario_inserta_form_validate(&$form, &$form_state){
//   if($form_state['values']['nombre'] == 'King Kong'){
//     //We notify the form API that this field has failed.
//     form_set_error('nombre', t('King Kong no es una persona'));
//   }
// }

/**
 * Handle post_validate form submission.
 */
function formulario_inserta_form_submit(&$form, &$form_state){
  $nombre = $form_state['values']['nombre'];
  $apellido = $form_state['values']['apellido'];
  $cedula = $form_state['values']['cedula'];
  $direccion = $form_state['values']['direccion'];
  $empleo = $form_state['values']['empleo'];
  $vocacion = $form_state['values']['vocacion'];
  $educacion = $form_state['values']['educacion'];
  db_insert('datos_formulario')
    ->fields(array('nombre', 'apellido', 'cedula', 'direccion', 'empleo', 'vocacion', 'educacion'))
    ->values(array('nombre' => $nombre, 'apellido' => $apellido, 'cedula' => $cedula, 'direccion' => $direccion, 'empleo' => $empleo, 'vocacion' => $vocacion, 'educacion' => $educacion,))
    ->execute();
  $form_state['redirect'] = 'formulario_consulta';
}