<?php
/**
 * Centro Nacional de Desarrollo e Investigación de Tecnologías Libres (CENDITEL)
 * CENDITEL, Mérida - Venezuela
 * Dirección de Desarrollo
 * Módulo Drupal para crear un formulario y luego alterarlo con un hook
 * @author Ing. Angelo Osorio
 * @date 08-11-2017 // (dd,mm,yyyy)
 * @version 1.-dev // (1.0)
 * @file formulario_modifica.module
 */



/**
 * Implements hook_menu().
 */
function formulario_modifica_menu() {
  $items['form_alter'] = array(
    'title' => 'Form Alter',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('formulario_modifica_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM
  );

  return $items;
}


/**
 * Implements hook_form().
 */
function formulario_modifica_form($form, &$form_state) {
  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Nombre'),
    '#required' => TRUE,
    '#description' => t('Introduce tu nombre'),
  );
  return $form;
}

/**
 * Implements hook_form_alter().
 */
function formulario_modifica_form_alter(&$form, &$form_state, $form_id) {
  if (1 == 1) {
    $form['lastname'] = array(
      '#type' => 'textfield',
      '#title' => t('Apellido'),
      '#required' => TRUE,
      '#description' => t('Introduce tu apellido'),
    );
  }
}